(function() {var implementors = {};
implementors["yukikaze"] = [{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"yukikaze/client/response/extractor/struct.RawBody.html\" title=\"struct yukikaze::client::response::extractor::RawBody\">RawBody</a>",synthetic:false,types:["yukikaze::client::response::extractor::RawBody"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"enum\" href=\"yukikaze/client/response/extractor/enum.Text.html\" title=\"enum yukikaze::client::response::extractor::Text\">Text</a>",synthetic:false,types:["yukikaze::client::response::extractor::Text"]},{text:"impl&lt;J:&nbsp;<a class=\"trait\" href=\"https://docs.rs/serde/1.0.70/serde/de/trait.DeserializeOwned.html\" title=\"trait serde::de::DeserializeOwned\">DeserializeOwned</a>&gt; <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"enum\" href=\"yukikaze/client/response/extractor/enum.Json.html\" title=\"enum yukikaze::client::response::extractor::Json\">Json</a>&lt;J&gt;",synthetic:false,types:["yukikaze::client::response::extractor::Json"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"yukikaze/client/response/extractor/struct.FileBody.html\" title=\"struct yukikaze::client::response::extractor::FileBody\">FileBody</a>",synthetic:false,types:["yukikaze::client::response::extractor::FileBody"]},{text:"impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/future/trait.Future.html\" title=\"trait futures::future::Future\">Future</a> for <a class=\"struct\" href=\"yukikaze/client/response/struct.FutureResponse.html\" title=\"struct yukikaze::client::response::FutureResponse\">FutureResponse</a>",synthetic:false,types:["yukikaze::client::response::FutureResponse"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
